(async () => {
    const TARGET_USERNAME = "YOUR_NGL_USERNAME";
    const JUMLAH_PESAN = 20;
    const DELAY_MIN = 500;
    const DELAY_MAX = 1000;

    let username = TARGET_USERNAME;
    if (!username) {
        const urlPath = window.location.pathname.replace("/", "");
        if (!urlPath) return;
        username = urlPath;
    }

    const TEMPLATES = [
        "hai",
        "halo",
        "hey",
        "hei",
        "yo",
        "hiii",
        "hey hey",
        "oy",
        "haloo",
        "hey lagi",
        "lagi ngapain",
        "lagi apa",
        "lagi online",
        "masih hidup",
        "gabut banget",
        "lagi gabut",
        "sedang apa",
        "lagi sibuk",
        "ngapain sekarang",
        "lagi di mana",
        "udah makan",
        "udah mandi",
        "udah tidur",
        "belum tidur",
        "belum makan",
        "kenapa belum tidur",
        "kenapa belum makan",
        "udah bangun",
        "baru bangun",
        "masih ngantuk",
        "baru bangun tidur",
        "udah siang",
        "udah malem",
        "udah pagi",
        "udah sore",
        " hari ini panas",
        "hari ini hujan",
        "ujan terus nih",
        "panas banget",
        "dingin banget",
        "gerah banget",
        "capek banget",
        "lelah banget",
        "ngantuk banget",
        "lapar banget",
        "haus banget",
        "bosan banget",
        "gabut banget",
        "bosen banget",
        "pusing banget",
        "pusing",
        "sebel banget",
        "kesel banget",
        "jengkel banget",
        "sabar ya",
        "sabar dulu",
        "tenang dulu",
        "santai dulu",
        "santai aja",
        " rileks",
        "chill dulu",
        "ayok",
        "yuk",
        "ayok lah",
        "yuk lah",
        "gas",
        "gas lah",
        "lanjut",
        "lanjut lah",
        "terus",
        "terus apa",
        "lalu apa",
        "trus gimana",
        "gimana",
        "gimana nih",
        "gimana caranya",
        "bisa gak",
        "bisa nggak",
        "bisa ga",
        "bisa toh",
        "gak bisa",
        "nggak bisa",
        "ga bisa",
        "gak bisa ya",
        "emang bisa",
        "bener gak",
        "bener nggak",
        "bener ga",
        "beneran",
        "serius",
        "seriusan",
        "serius nih",
        "beneran nih",
        "jujur",
        "jujuran dong",
        "jujur deh",
        "bener gak sih",
        "bener ga sih",
        "yakin",
        "yakin nih",
        "yakin banget",
        "yakin gak",
        "yakin nggak",
        "pasti",
        "pasti banget",
        "pasti bisa",
        "pasti gak",
        "mungkin",
        "mungkin aja",
        "mungkin sih",
        "kayaknya",
        "kayaknya sih",
        "kayaknya bisa",
        "kayaknya gak",
        "sepertinya",
        "sepertinya sih",
        "sepertinya bisa",
        "rasanya",
        "rasanya bisa",
        "rasanya gak",
        "gatau",
        "ga tau",
        "nggak tau",
        "gak tau",
        "tidak tau",
        "entah",
        "entah lah",
        "entahlah",
        "gak paham",
        "ga paham",
        "nggak paham",
        "gak ngerti",
        "ga ngerti",
        "nggak ngerti",
        "gak jelas",
        "ga jelas",
        "nggak jelas",
        "gak ngaruh",
        "ga ngaruh",
        "nggak ngaruh",
        "punya pacar belum",
        "punya pacar belum sih",
        "punya pacar ga",
        "single",
        "jomblo",
        "masih jomblo",
        "masih single",
        "single kan",
        "jomblo kan",
        "pacarnya siapa",
        "siapa pacarnya",
        "siapa dia",
        "suka siapa",
        " lagi suka siapa",
        "crush siapa",
        "lagi crush siapa",
        "tipe kamu yang gimana",
        "tipe kamu apa",
        "mau yang kayak gimana",
        "cari yang kayak gimana",
        "idealnya kayak gimana",
        "kalo diputusin nangis gak",
        "pernah nangis gak",
        "pernah nangis karena seseorang gak",
        "pernah patah hati gak",
        "pernah broken heart gak",
        "patah hati belum",
        "broken heart belum",
        "pernah ngecry gak",
        "terakhir nangis kapan",
        "kenapa nangis",
        "nangis karena apa",
        "ada yang bikin sedih",
        "sedih nih",
        "sedih banget",
        "haru banget",
        "terharu",
        "terharu banget",
        "kangen",
        "kangen banget",
        "rindu",
        "rindu banget",
        "kangen seseorang",
        "lagi kangen siapa",
        "kangen sama siapa",
        "rindu sama siapa",
        "pengen ketemu",
        "pengen banget ketemu",
        "kapan bisa ketemu",
        "pengen ngobrol",
        "pengen banget ngobrol",
        "pengen ngobrol lama",
        "chat aja",
        "dm aja",
        "balas dong",
        "balas chat",
        "bales dong",
        "bales chat",
        "baca dong",
        "baca dulu",
        "cepat balas",
        "lambat banget balas",
        "kenapa lama balas",
        "lama banget sih balasnya",
        "kok gak pernah balas",
        "gak pernah bales",
        "dibaca aja gak dibales",
        "centang biru mulu",
        "selalu centang biru",
        "pengen bilang sesuatu",
        "ada yang mau dibilang",
        "ada yang pengen dibilang",
        "mau bilang sesuatu",
        "tapi gak tau harus mulai dari mana",
        "tapi ga tau mulai dari mana",
        "tapi nggak tau mulai dari mana",
        "gak berani bilang",
        "ga berani bilang",
        "nggak berani bilang",
        "takut",
        "takut banget",
        "takut ditolak",
        "takut gak diterima",
        "takut salah",
        "takut salah ngomong",
        "takut jelek",
        "takut mengganggu",
        "takut nyebelin",
        "takut gak enak",
        "gak enak banget",
        "ga enak banget",
        "nggak enak banget",
        "gak enak hati",
        "ga enak hati",
        "nggak enak hati",
        "mengganggu gak",
        "mengganggu ga",
        "ganggu gak",
        "ganggu ga",
        "berasa mengganggu",
        "takut mengganggu",
        "maaf mengganggu",
        "maaf ganggu",
        "sorry ganggu",
        "sorry mengganggu",
        "maaf ya",
        "maaf banget",
        "sorry ya",
        "sorry banget",
        "permisi",
        "permisi ya",
        "kamu itu",
        "kamu tuh",
        "lu tuh",
        "kamu orangnya",
        "kamu tipe orang yang",
        "kamu tuh beda",
        "kamu beda banget",
        "kamu unik",
        "kamu unik banget",
        "kamu spesial",
        "kamu spesial banget",
        "kamu berbeda",
        "kamu tidak seperti yang lain",
        "kamu gak kayak yang lain",
        "kamu ga kayak orang lain",
        "kamu beda sendiri",
        "kamu tuh asik",
        "kamu asik banget",
        "orangnya asik",
        "enak diajak ngobrol",
        "pengen deket sama kamu",
        "pengen banget deket sama kamu",
        "pengen kenal lebih dekat",
        "pengen banget kenal lebih dekat",
        "bisa kenalan gak",
        "bisa ga kenalan",
        "kenalan yuk",
        "kenalan dong",
        "temenan yuk",
        "temenan dong",
        "punya temen gak",
        "punya sahabat gak",
        "sahabat kamu siapa",
        "temen dekat kamu siapa",
        "paling deket sama siapa",
        "dekat sama siapa sekarang",
        "lagi deket sama siapa",
        "lagi Approaching siapa",
        "lagi deketan sama siapa",
        "ada yang dekat gak",
        "ada yang mendekatin gak",
        "lagi didekatin siapa",
        "ada yang suka gak",
        "ada yang suka sama kamu gak",
        "ada yang naksir gak",
        "ada yang naksir sama kamu gak",
        "siapa yang suka sama kamu",
        "siapa yang naksir kamu",
        "tau gak siapa ini",
        "tebak siapa ini",
        "coba tebak siapa",
        "tebak dong siapa ini",
        "ini siapa ya",
        "tahu gak ini siapa",
        "kira kira ini siapa",
        "pusing tebak tebakan",
        "gak usah ditebak",
        "jangan ditebak",
        "gak akan pernah tau",
        "ga akan pernah tau",
        "rahasia",
        "ini rahasia",
        "rahasia dong",
        "biar jadi rahasia",
        "gak akan bilang",
        "ga akan bilang",
        "nggak akan bilang",
        "gak bakal bilang",
        "ga bakal bilang",
        "nggak bakal bilang",
        "gak bakal ngaku",
        "ga bakal ngaku",
        "nggak bakal ngaku",
        "biarin aja",
        "biarin deh",
        "gak usah dipikirin",
        "ga usah dipikirin",
        "nggak usah dipikirin",
        "skip aja",
        "skip aja kalau gak penting",
        "baca aja gak usah dipikirin",
        "jangan dibaca",
        "jangan dibaca serius",
        "gak usah serius",
        "ga usah serius",
        "nggak usah serius",
        "bercanda",
        "canda",
        "just kidding",
        "pk",
        "gapernah kesel",
        "pernah kesel gak",
        "pernah marah gak",
        "terakhir marah kapan",
        "kenapa marah",
        "marah karena apa",
        "paling kesel sama siapa",
        "paling sebel sama siapa",
        "yang paling bikin kesel siapa",
        "suka marah gak",
        "temperamen gak",
        "emosian gak",
        "gampang marah gak",
        "sabar gak",
        "sabar banget gak",
        "paling sabar sampai sejauh mana",
        "hal paling bikin kesel apa",
        "hal yang paling dibenci apa",
        "paling benci apa",
        "paling gak suka apa",
        "paling males ngapain",
        "paling suka ngapain",
        "hobi apa",
        "hobi kamu apa",
        "suka apa",
        "suka banget apa",
        "makanan favorit",
        "minuman favorit",
        "film favorit",
        "lagu favorit",
        "warna favorit",
        "tempat favorit",
        "tempat yang pengen dikunjungi",
        "pengen ke mana",
        "pengen banget ke mana",
        "negara yang pengen dikunjungi",
        "negara mana yang pengen dikunjungi",
        "kalo liburan mau ke mana",
        "mau liburan ke mana",
        "pengen liburan",
        "pengen banget liburan",
        "butuh liburan",
        "butuh banget liburan",
        "capek butuh liburan",
        "pengen istirahat",
        "pengen banget istirahat",
        "istirahat dulu",
        "istirahat aja",
        "jangan dipaksa",
        "gak usah dipaksa",
        "ga usah dipaksa",
        "nggak usah dipaksa",
        "jangan dipersulit",
        "gak usah dipersulit",
        "ga usah dipersulit",
        "nggak usah dipersulit",
        "santai aja sudah",
        "santai saja",
        "santai dah",
        "santai dulu dah",
        "tenang aja",
        "tenang dah",
        "tenang dulu",
        "pokoknya santai",
        "yang penting santai",
        "yang penting sehat",
        "yang penting bahagia",
        "yang penting happy",
        "yang penting tidak menyakiti",
        "yang penting gak nyakitin",
        "yang penting ga nyakitin",
        "jangan menyakiti",
        "jangan nyakitin",
        "jangan bikin sedih",
        "jangan bikin nangis",
        "jangan bikin kecewa",
        "jangan kecewain",
        "jangan disappointing",
        "jangan dissapointing",
        "jangan bikin dissapointed",
        "semoga bahagia",
        "semoga sehat selalu",
        "semoga lancar",
        "semoga lancar selalu",
        "semoga berhasil",
        "semoga sukses",
        "semoga mujur",
        "semoga beruntung",
        "semoga diberkahi",
        "semoga dimudahkan",
        "semoga dipermudah",
        "semoga dilancarkan",
        "semoga dilindungi",
        "semoga selamat",
        "jaga kesehatan",
        "jaga diri baik baik",
        "jaga kesehatan ya",
        "jaga diri ya",
        "makan yang teratur",
        "tidur yang cukup",
        "jangan lupa makan",
        "jangan lupa tidur",
        "jangan lupa istirahat",
        "jangan begadang terus",
        "jangan lupa minum air",
        "jangan skip makan",
        "jangan terlalu lelah",
        "jangan terlalu capek",
        "jangan terlalu pusing",
        "jangan terlalu overthinking",
        "berhenti overthinking",
        "stop overthinking",
        "jangan overthink",
        "jangan mikir terlalu jauh",
        "jangan mikirin hal gak penting",
        "gak usah dipikirin yang gak penting",
        "ga usah dipikirin yang ga penting",
        "nggak usah dipikirin yang nggak penting",
        "fokus yang penting aja",
        "fokus yang bener aja",
        "pikirin yang positif aja",
        "mikir yang positif aja",
        "thinking positive aja",
        "positive thinking",
        "semangat",
        "semangat ya",
        "semangat terus",
        "tetap semangat",
        "jangan menyerah",
        "jangan pernah menyerah",
        "jangan mudah menyerah",
        "pasti bisa",
        "kamu pasti bisa",
        "yakin kamu bisa",
        "aku yakin kamu bisa",
        "percaya diri",
        "lebih percaya diri",
        "jangan rendah diri",
        "jangan merasa rendah",
        "kamu sudah cukup",
        "kamu udah cukup",
        "kamu sudah bagus",
        "kamu udah bagus",
        "kamu sudah hebat",
        "kamu udah hebat",
        "kamu sudah berusaha",
        "kamu udah berusaha",
        "itu sudah cukup",
        "itu udah cukup",
        "gak usah terlalu sempurna",
        "ga usah terlalu sempurna",
        "nggak usah terlalu sempurna",
        "gak ada yang sempurna",
        "ga ada yang sempurna",
        "nggak ada yang sempurna",
        "manusia gak sempurna",
        "manusia ga sempurna",
        "manusia nggak sempurna",
        "wajar gak sempurna",
        "wajar ga sempurna",
        "wajar nggak sempurna",
        "yang penting mau berusaha",
        "yang penting berusaha",
        "yang penting berproses",
        "yang penting jalan",
        "yang penting ada kemajuan",
        "yang penting nggak mundur",
        "yang penting ga mundur",
        "yang penting gak mundur",
        "pelan pelan aja",
        "pelan pelan dulu",
        "step by step",
        "satu per satu",
        "gak usah terburu buru",
        "ga usah terburu buru",
        "nggak usah terburu buru",
        "jangan terburu buru",
        "sabar prosesnya",
        "sabar aja prosesnya",
        "nikmati prosesnya",
        "jalani aja dulu",
        "jalanin aja dulu",
        "nanti juga sampai",
        "nanti juga tercapai",
        "nanti juga terwujud",
        "yang penting mulai",
        "yang penting jalan",
        "yang penting mulai dulu",
        "mulai dari yang kecil",
        "mulai dari yang mudah",
        "mulai dari sekarang",
        "jangan ditunda",
        "jangan ditunda lagi",
        "jangan selalu nanti",
        "jangan selalu besok",
        "sekarang atau tidak sama sekali",
        "now or never",
        "lakukan sekarang",
        "gas sekarang",
        "mulai sekarang"
    ];

    const TYPO_MAP = {
        "kamu": ["km", "kmu", "kamuu", "kmuu"],
        "aku": ["aq", "ak", "akuu", "akku"],
        "gak": ["gk", "ga", "nggak", "gak"],
        "banget": ["bgt", "bangett", "bangeet", "bnget"],
        "lagi": ["lg", "lgi", "lagi"],
        "apa": ["apa", "pa"],
        "yang": ["yg", "yng", "yang"],
        "sih": ["sih", "cih"],
        "tau": ["tw", "thu", "tau", "tahu"],
        "belum": ["blm", "belom", "belum"],
        "sudah": ["udah", "sdh", "udh", "sudah"],
        "sama": ["sma", "sama"],
        "ini": ["ni", "nih", "ini"],
        "dengan": ["dgn", "dengan"],
        "karena": ["karna", "krn", "karena"],
        "tidak": ["tdk", "gak", "ga", "tidak"],
        "jadi": ["jdi", "jadi"],
        "kalau": ["klo", "kalo", "kalau"],
        "tapi": ["tpi", "tp", "tapi"],
        "bisa": ["bsa", "bisa"],
        "untuk": ["untk", "utk", "untuk"],
        "saja": ["aja", "sj", "saja"],
        "sesuatu": ["sstu", "sstu", "sesuatu"],
        "pengen": ["pgn", "pengen", "pngn"],
        "kenapa": ["knp", "knappa", "kenapa"],
        "nanti": ["nti", "nantti", "nanti"],
        "sekarang": ["skrng", "skarang", "skrg", "sekarang"],
        "selalu": ["slalu", "slalu", "selalu"],
        "pernah": ["prnh", "pnrh", "pernah"],
        "sedang": ["sdg", "sedang"],
        "masih": ["msh", "masih"],
        "sudah": ["udh", "sdh", "sudah"],
        "banyak": ["bnyk", "byk", "banyak"],
        "memang": ["mmg", "memang"],
        "memangnya": ["mmgnya", "memangnya"],
        "sebenarnya": ["sebenernya", "sbenernya", "sebenarnya"],
        "sebenernya": ["sbnernya", "sebenernya"],
        "harus": ["hrs", "harus"],
        "nggak": ["nggak", "ngak", "ngga"],
        "diajak": ["djak", "diajak"],
        "mengganggu": ["mgganggu", "mngganggu", "mengganggu"],
        "mengapa": ["mengapa", "knppa", "mngapa"],
        "mengatakan": ["mngatakan", "mengatakan"],
        "berhasil": ["brhasil", "berhasil"],
        "berhenti": ["brhenti", "berhenti"],
        "berusaha": ["brusaha", "berusaha"],
        "diperlukan": ["dperlukan", "diperlukan"],
        "dipikirkan": ["dpikirkan", "dipikirkan"],
        "dipersulit": ["dpersulit", "dipersulit"],
        "dilindungi": ["dlindungi", "dilindungi"],
        "dilancarkan": ["dlancarkan", "dilancarkan"],
        "diberkahi": ["dberkahi", "diberkahi"],
        "dimudahkan": ["dmudahkan", "dimudahkan"],
        "dikecewakan": ["dkecewakan", "dikecewakan"],
        "menyakiti": ["nyakitin", "menyakiti"],
        "membuat": ["mbuat", "membuat"],
        "melakukan": ["mlakukan", "melakukan"],
        "mendekati": ["mndekati", "mendekati"],
        "mendekatin": ["mndekatin", "mendekatin"],
        "mengganggu": ["mgganggu", "mengganggu"],
        "mengenal": ["mngenal", "mengenal"],
        "menyebabkan": ["menyebabkan", "mnyebabkan"],
        "menyebalkan": ["menyebalkan", "mnyebalkan"],
        "menyenangkan": ["menyenangkan", "mnyenangkan"],
        "menghibur": ["mnghibur", "menghibur"],
        "memberikan": ["memberikan", "mberikan"],
        "membuktikan": ["mmbuktikan", "membuktikan"],
        "mempersiapkan": ["mmpersiapkan", "mempersiapkan"],
        "menunjukkan": ["mnunjukkan", "menunjukkan"],
        "menyadari": ["menyadari", "mnyadari"],
        "menginginkan": ["mnginginkan", "menginginkan"],
        "mendapatkan": ["mndapatkan", "mendapatkan"],
        "menemukan": ["mnemukan", "menemukan"],
        "menghabiskan": ["mnghabiskan", "menghabiskan"],
        "melewati": ["mlewati", "melewati"],
        "mengalami": ["mngalami", "mengalami"],
        "merasakan": ["merasakan", "mrasakan"],
        "mempunyai": ["mpunyai", "mempunyai"],
        "mengubah": ["mngubah", "mengubah"],
        "menyimpan": ["menyimpan", "mnyimpan"],
        "melupakan": ["mlupakan", "melupakan"],
        "menghilangkan": ["mnghilangkan", "menghilangkan"],
        "menghargai": ["mnghargai", "menghargai"],
        "menerima": ["mnerima", "menerima"],
        "menolak": ["mnolak", "menolak"],
        "mengizinkan": ["mngizinkan", "mengizinkan"],
        "melarang": ["mlarang", "melarang"],
        "menghindari": ["mnhindari", "menghindari"],
        "menghadapi": ["mnhadapi", "menghadapi"],
        "menyelesaikan": ["mnyelesaikan", "menyelesaikan"],
        "mengatasi": ["mngatasi", "mengatasi"],
        "membangun": ["mbangun", "membangun"],
        "menjaga": ["mnjaga", "menjaga"],
        "melindungi": ["mlindungi", "melindungi"],
        "menyayangi": ["mnyayangi", "menyayangi"],
        "mencintai": ["mncintai", "mencintai"],
        "menyukai": ["mnyukai", "menyukai"],
        "mengagumi": ["mngagumi", "mengagumi"],
        "menghormati": ["mnghormati", "menghormati"],
        "mempercayai": ["mpercayai", "mempercayai"],
        "mengandalkan": ["mngandalkan", "mengandalkan"],
        "menyadari": ["mnyadari", "menyadari"],
        "mempertimbangkan": ["mpertimbangkan", "mempertimbangkan"],
        "mengevaluasi": ["mngevaluasi", "mengevaluasi"],
        "mengembangkan": ["mngembangkan", "mengembangkan"],
        "meningkatkan": ["mningkatkan", "meningkatkan"],
        "memperbaiki": ["mperbaiki", "memperbaiki"],
        "mengoptimalkan": ["mngoptimalkan", "mengoptimalkan"],
        "memaksimalkan": ["maksimalkan", "memaksimalkan"],
        "merealisasikan": ["mrealisasikan", "merealisasikan"],
        "mewujudkan": ["mwujudkan", "mewujudkan"],
        "mengesampingkan": ["mngesampingkan", "mengesampingkan"],
        "mengabaikan": ["mngabaikan", "mengabaikan"],
        "menyepelekan": ["mnyelepekan", "menyepelekan"],
        "meremehkan": ["mremehkan", "meremehkan"],
        "menunderestimate": ["munderestimate", "menunderestimate"],
        "merusak": ["mrusak", "merusak"],
        "menghancurkan": ["mnghancurkan", "menghancurkan"],
        "mempermalukan": ["mpermalukan", "mempermalukan"],
        "menjatuhkan": ["njatuhkan", "menjatuhkan"],
        "menyudutkan": ["mnyudutkan", "menyudutkan"],
        "menuduh": ["mnuduh", "menuduh"],
        "memfitnah": ["mfitnah", "memfitnah"],
        "menyebar": ["mnyebar", "menyebar"],
        "menyebarkan": ["mnyebarkan", "menyebarkan"],
        "mengungkapkan": ["mngungkapkan", "mengungkapkan"],
        "membocorkan": ["mbocorkan", "membocorkan"],
        "mengungsi": ["mngungsi", "mengungsi"],
        "menyelamatkan": ["mnyelamatkan", "menyelamatkan"],
        "menolong": ["ntolong", "menolong"],
        "membantu": ["mbantu", "membantu"],
        "mendukung": ["mndukung", "mendukung"],
        "menyokong": ["mnyokong", "menyokong"],
        "mendorong": ["mndorong", "mendorong"],
        "memotivasi": ["mmotivasi", "memotivasi"],
        "menginspirasi": ["mnginspirasi", "menginspirasi"],
        "mengajarkan": ["mngajarkan", "mengajarkan"],
        "membimbing": ["mbimbing", "membimbing"],
        "menuntun": ["mntuntun", "menuntun"],
        "mengarahkan": ["mngrahkan", "mengarahkan"],
        "menunjukkan": ["mnunjukkan", "menunjukkan"],
        "menerangkan": ["mnerangkan", "menerangkan"],
        "menjelaskan": ["njelaskan", "menjelaskan"],
        "mengartikan": ["mngartikan", "mengartikan"],
        "menerjemahkan": ["mnerjemahkan", "menerjemahkan"],
        "menginterpretasikan": ["mnginterpretasikan", "menginterpretasikan"],
        "memahami": ["mpahami", "memahami"],
        "mengerti": ["mngerti", "mengerti"],
        "menangkap": ["ntangkap", "menangkap"],
        "merebut": ["mrebut", "merebut"],
        "mengambil": ["mngambil", "mengambil"],
        "meminjam": ["mpinjam", "meminjam"],
        "meminjamkan": ["mpinjamkan", "meminjamkan"],
        "mengembalikan": ["mngembalikan", "mengembalikan"],
        "mengirim": ["mngirim", "mengirim"],
        "mengirimkan": ["mngirimkan", "mengirimkan"],
        "menerima": ["mnerima", "menerima"],
        "menolak": ["mnolak", "menolak"],
        "membatalkan": ["mbatalkan", "membatalkan"],
        "memperbarui": ["mperbarui", "memperbarui"],
        "memperbaharui": ["mperbaharui", "memperbaharui"],
        "memperbarui": ["mperbarui", "memperbarui"],
        "menambahkan": ["mnambahkan", "menambahkan"],
        "mengurangi": ["mngurangi", "mengurangi"],
        "menghapus": ["mnhapus", "menghapus"],
        "menghilangkan": ["mnghilangkan", "menghilangkan"],
        "membersihkan": ["mbersihkan", "membersihkan"],
        "merapikan": ["mrapikan", "merapikan"],
        "mengatur": ["mngatur", "mengatur"],
        "mengorganisir": ["mngorganisir", "mengorganisir"],
        "merencanakan": ["mrencanakan", "merencanakan"],
        "menjadwalkan": ["njadwalkan", "menjadwalkan"],
        "melaksanakan": ["mlaksanakan", "melaksanakan"],
        "mengeksekusi": ["mneksekusi", "mengeksekusi"],
        "mengoperasikan": ["mngoperasikan", "mengoperasikan"],
        "mengendalikan": ["mngendalikan", "mengendalikan"],
        "mengawasi": ["mngawasi", "mengawasi"],
        "memantau": ["mpantau", "memantau"],
        "mengecek": ["ngecek", "mengecek"],
        "memeriksa": ["meriksa", "memeriksa"],
        "menguji": ["mnguji", "menguji"],
        "menganalisis": ["mnganalisis", "menganalisis"],
        "menyelidiki": ["mnyelidiki", "menyelidiki"],
        "mengeksplorasi": ["mngeksplorasi", "mengeksplorasi"],
        "menemukan": ["mnemukan", "menemukan"],
        "menemui": ["mntemui", "menemui"],
        "mengunjungi": ["mngunjungi", "mengunjungi"],
        "mendatangi": ["mndatangi", "mendatangi"],
        "mendekati": ["mndekati", "mendekati"],
        "menyapa": ["mnyapa", "menyapa"],
        "mengajak": ["mngajak", "mengajak"],
        "mengundang": ["mngundang", "mengundang"],
        "meminta": ["minta", "meminta"],
        "memohon": ["mphohon", "memohon"],
        "memerintah": ["merintah", "memerintah"],
        "memerintahkan": ["merintahkan", "memerintahkan"],
        "melarang": ["mlarang", "melarang"],
        "melarangkan": ["mlarangkan", "melarangkan"],
        "mengizinkan": ["mngizinkan", "mengizinkan"],
        "memperbolehkan": ["mperbolehkan", "memperbolehkan"],
        "menghalangi": ["mnghalangi", "menghalangi"],
        "mencegah": ["mncegah", "mencegah"],
        "menghambat": ["mnghambat", "menghambat"],
        "menghalang": ["mnghalang", "menghalang"],
        "mengganggu": ["mgganggu", "mengganggu"],
        "mengusik": ["mngusik", "mengusik"],
        "mengganggu": ["mgganggu", "mengganggu"],
        "mempermainkan": ["mpermainkan", "mempermainkan"],
        "memperolok": ["mperolok", "memperolok"],
        "mengejek": ["ngejek", "mengejek"],
        "mengolok": ["mngolok", "mengolok"],
        "menertawakan": ["ntertawakan", "menertawakan"],
        "mempermalukan": ["mpermalukan", "mempermalukan"],
        "menghina": ["mnhina", "menghina"],
        "merendahkan": ["mrendahkan", "merendahkan"],
        "menyindir": ["mnyindir", "menyindir"],
        "menyindir": ["mnyindir", "menyindir"],
        "mengkritik": ["mngkritik", "mengkritik"],
        "mengomentari": ["mngomentari", "mengomentari"],
        "menanggapi": ["ntanggapi", "menanggapi"],
        "merespons": ["mrespon", "merespons"],
        "membalas": ["mbalas", "membalas"],
        "menjawab": ["njawab", "menjawab"],
        "mengakui": ["mngakui", "mengakui"],
        "mengakui": ["mngakui", "mengakui"],
        "mengingkari": ["mngingkari", "mengingkari"],
        "menolak": ["mnolak", "menolak"],
        "menolak": ["mnolak", "menolak"],
        "menerima": ["mnerima", "menerima"],
        "menerima": ["mnerima", "menerima"],
        "mengambil": ["mngambil", "mengambil"],
        "mengambil": ["mngambil", "mengambil"]
    };

    function randInt(min, max) {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

    function randomPick(arr) {
        return arr[Math.floor(Math.random() * arr.length)];
    }

    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    function humanize(text) {
        let result = text;

        for (const [kataAsli, variasi] of Object.entries(TYPO_MAP)) {
            if (result.includes(kataAsli) && Math.random() > 0.35) {
                result = result.replace(kataAsli, randomPick(variasi));
            }
        }

        if (Math.random() < 0.15) {
            result = result.toLowerCase();
        }

        if (Math.random() < 0.12) {
            const words = result.split(" ");
            if (words.length > 2) {
                const idx = randInt(1, words.length - 2);
                words[idx] = words[idx] + "  ";
                result = words.join(" ");
            }
        }

        if (Math.random() < 0.1) {
            result = result.replace(/\?\s*$/, "");
        }

        if (Math.random() < 0.15) {
            result = result + "...";
        }

        if (Math.random() < 0.1 && result.length > 5) {
            const tambahan = randomPick([" sih", " dong", " lah", " banget", " kok"]);
            if (!result.endsWith(tambahan.trim())) {
                result = result + tambahan;
            }
        }

        if (Math.random() < 0.1 && result.length > 3) {
            const lastChar = result.trim().slice(-1);
            if (lastChar.match(/[a-z]/i)) {
                result = result.trim() + lastChar;
            }
        }

        if (Math.random() < 0.08 && result.length > 5) {
            const filler = randomPick(["hmm ", "btw ", "anu ", "gini ", "nah ", "trus "]);
            result = filler + result;
        }

        if (Math.random() < 0.07 && result.length > 5) {
            const tanya = randomPick(["?", "??", "??", " nggak?", " ga?", " gak?"]);
            if (!result.endsWith("?")) {
                result = result + tanya;
            }
        }

        return result;
    }

    function generateMessages(count) {
        const messages = new Set();
        let safety = 0;

        while (messages.size < count && safety < count * 10) {
            const base = randomPick(TEMPLATES);
            messages.add(humanize(base));
            safety++;
        }

        return Array.from(messages);
    }

    async function sendNgl(user, msg) {
        try {
            const res = await fetch("https://ngl.link/api/submit", {
                method: "POST",
                headers: {
                    "Content-Type": "application/x-www-form-urlencoded",
                    "Origin": "https://ngl.link",
                    "Referer": `https://ngl.link/${user}`
                },
                body: new URLSearchParams({
                    username: user,
                    question: msg,
                    deviceId: crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
                }).toString()
            });
            return res.ok;
        } catch (e) {
            return false;
        }
    }

    console.clear();
    console.log("%cNGL SENDER - BAHASA INDONESIA", "color: #2ecc71; font-size: 16px; font-weight: bold;");
    console.log(`%cTarget : ${username}`, "color: #4ecdc4; font-size: 12px;");
    console.log(`%cJumlah : ${JUMLAH_PESAN} pesan`, "color: #4ecdc4; font-size: 12px;");
    console.log(`%cDelay  : ${DELAY_MIN/1000}s - ${DELAY_MAX/1000}s`, "color: #4ecdc4; font-size: 12px;");
    console.log("%c----------------------------------", "color: gray;");
    console.log("%cMulai NGL spam...", "color: yellow;");

    await sleep(3000);

    const messages = generateMessages(JUMLAH_PESAN);
    let berhasil = 0;
    let gagal = 0;

    for (let i = 0; i < messages.length; i++) {
        const pesan = messages[i];
        const status = await sendNgl(username, pesan);

        if (status) {
            berhasil++;
            console.log(`%c[${i + 1}/${messages.length}] ✅ "${pesan}"`, "color: #2ecc71;");
        } else {
            gagal++;
            console.log(`%c[${i + 1}/${messages.length}] ❌ "${pesan}"`, "color: #e74c3c;");
        }

        if (i < messages.length - 1) {
            const delay = randInt(DELAY_MIN, DELAY_MAX);
            console.log(`%c   ⏳ ${(delay / 1000).toFixed(1)}s...`, "color: gray;");
            await sleep(delay);
        }
    }

    console.log("%c----------------------------------", "color: gray;");
    console.log("%c📊 STATISTIK", "color: #f1c40f; font-size: 14px; font-weight: bold;");
    console.log(`%c✅ ${berhasil} | ❌ ${gagal}`, "color: #4ecdc4; font-size: 12px;");
})();